*&---------------------------------------------------------------------*
*&  Include           CUSTOMER_MANAGEMENT_SERVICE_SEL
*&---------------------------------------------------------------------*

*-------------------------Program mode-------------------------*
SELECTION-SCREEN BEGIN OF BLOCK bk1 WITH FRAME TITLE TEXT-001.
  PARAMETERS: rbut1 RADIOBUTTON GROUP gr1 DEFAULT 'X' USER-COMMAND uc1 MODIF ID id9,
              rbut2 RADIOBUTTON GROUP gr1 MODIF ID id9,
              rbut3 RADIOBUTTON GROUP gr1 MODIF ID id9,
              rbut4 RADIOBUTTON GROUP gr1 MODIF ID id9,
              rbut5 RADIOBUTTON GROUP gr1 MODIF ID id9.
SELECTION-SCREEN END OF BLOCK bk1.
*-------------------------New customer's data-------------------------*
SELECTION-SCREEN BEGIN OF BLOCK bk2 WITH FRAME TITLE TEXT-002.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(15) TEXT-004 MODIF ID id1.
    PARAMETERS: p_kunnr TYPE kna1-kunnr MODIF ID id1.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(15) TEXT-005 MODIF ID id1.
    PARAMETERS: p_land1 TYPE kna1-land1 MODIF ID id1.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(15) TEXT-006 MODIF ID id1.
    PARAMETERS: p_name1 TYPE kna1-name1 MODIF ID id1.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(15) TEXT-007 MODIF ID id1.
    PARAMETERS: p_ort01 TYPE kna1-ort01 MODIF ID id1.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(15) TEXT-008 MODIF ID id1.
    PARAMETERS: p_pstlz TYPE kna1-pstlz MODIF ID id1.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bk2.

SELECTION-SCREEN PUSHBUTTON 1(20) TEXT-009 USER-COMMAND fc1 MODIF ID id1.
*-------------------------Orders-------------------------*
SELECTION-SCREEN BEGIN OF BLOCK bk3 WITH FRAME TITLE TEXT-003.
  SELECT-OPTIONS: sl_kunnr FOR kna1-kunnr MODIF ID id2.
SELECTION-SCREEN END OF BLOCK bk3.

SELECTION-SCREEN PUSHBUTTON 1(20) TEXT-010 USER-COMMAND fc2 MODIF ID id2.
*-------------------------Delete a customer-------------------------*
SELECTION-SCREEN BEGIN OF BLOCK bk4 WITH FRAME TITLE TEXT-011.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(15) TEXT-004 MODIF ID id3.
    PARAMETERS: p_kunnr2 TYPE kna1-kunnr MODIF ID id3.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bk4.

SELECTION-SCREEN PUSHBUTTON 1(20) TEXT-011 USER-COMMAND fc3 MODIF ID id3.
*-------------------------Update a customer-------------------------*
SELECTION-SCREEN BEGIN OF BLOCK bk5 WITH FRAME TITLE TEXT-012.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(15) TEXT-004 MODIF ID id4.
    PARAMETERS: p_kunnr3 TYPE kna1-kunnr MODIF ID id4.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bk5.

SELECTION-SCREEN PUSHBUTTON 1(20) TEXT-015 USER-COMMAND fc4 MODIF ID id4.
*-------------------------Display a customer-------------------------*
SELECTION-SCREEN BEGIN OF BLOCK bk6 WITH FRAME TITLE TEXT-014.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(15) TEXT-004 MODIF ID id5.
    SELECT-OPTIONS: sl_kunn2 FOR kna1-kunnr MODIF ID id5.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bk6.

SELECTION-SCREEN PUSHBUTTON 1(20) TEXT-014 USER-COMMAND fc5 MODIF ID id5.
*-------------------------Updating panel-------------------------*
SELECTION-SCREEN BEGIN OF BLOCK bk7 WITH FRAME TITLE TEXT-013.
  SELECTION-SCREEN BEGIN OF BLOCK b8 WITH FRAME.
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(75) TEXT-017 MODIF ID id6.
    SELECTION-SCREEN END OF LINE.
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(75) TEXT-018 MODIF ID id6.
    SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN END OF BLOCK b8.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(15) TEXT-004 MODIF ID id6.
    PARAMETERS: p_kunnr4 TYPE kna1-kunnr MODIF ID id6.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(15) TEXT-005 MODIF ID id6.
    PARAMETERS: p_land12 TYPE kna1-land1 MODIF ID id6.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(15) TEXT-006 MODIF ID id6.
    PARAMETERS: p_name12 TYPE kna1-name1 MODIF ID id6.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(15) TEXT-007 MODIF ID id6.
    PARAMETERS: p_ort012 TYPE kna1-ort01 MODIF ID id6.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(15) TEXT-008 MODIF ID id6.
    PARAMETERS: p_pstlz2 TYPE kna1-pstlz MODIF ID id6.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bk7.

SELECTION-SCREEN PUSHBUTTON 1(20) TEXT-016 USER-COMMAND fc6 MODIF ID id6.

*TEXT ELEMENTS TO BE INCLUDED IN "TEXTS".
*-----------Text Symbols Sheet-----------
*001 - Program mode
*002 - New customer's data
*003 - Orders
*004 - Customer number
*005 - Country
*006 - Name
*007 - City
*008 - Postal code
*009 - Add customer
*010 - Find orders
*011 - Delete a customer
*012 - Update a customer
*013 - Updating panel
*014 - Display customers
*015 - Find customer
*016 - Update
*017 - The customer has been found. The data is displayed for every field to
*018 - change. Implement the changes and proceed.
*----------Selection Texts Sheet---------
*RBUT1 - New customer's insertion
*RBUT2 - Orders
*RBUT3 - Delete a customer
*RBUT4 - Update a customer
*RBUT5 - Display a customer
*sl_kunnr - Customer number